Central new network [WIP]
consindo/waka pull request #116
Opened 2018-06-21 10:21 UTC by mjdavidson

Need to think about how the list of all lines should look, maybe make a tweet about it
I think it should look like this:
-Central
--Frequent
--Peak
--Connector
--Local
-South
--Frequent
...

--this needs to be completed by July 7th--

2018-06-21 12:33 UTC, consindo commented
Also need to update the tests and make sure they pass

2018-07-07 06:20 UTC, mjdavidson commented
better late than never.

2018-07-07 08:47 UTC, consindo requested changes
need to fix some of the weird indentation

2018-07-07 08:47 UTC, consindo commented on server-worker/lines/nz-akl.js
> +  case 'NZB' || 'NZBML': // NZ Bus - metrolink
I didn't know this actually worked

2018-07-07 08:47 UTC, consindo commented on server-worker/lines/nz-akl.js
> +  let routes = []
Wow it used to be called todo

2018-07-07 08:47 UTC, consindo commented on server-worker/lines/nz-akl.js
> +  '22R': [['Rosebank Rd',        'City Centre','New North Rd']],
the indentation is a bit funny

2018-07-07 09:28 UTC, mjdavidson commented on server-worker/lines/nz-akl.js
> +  let routes = []
...

2018-07-07 11:03 UTC, mjdavidson commented
@consindo  this is done, will restructure the groups in the future

2018-07-07 11:15 UTC, consindo approved these changes
💯

2018-07-07 11:23 UTC, merged