fetch and display new line/route info with correct tz
consindo/waka pull request #167
Opened 2019-07-31 12:32 UTC by mjdavidson

2019-07-31 22:06 UTC, consindo requested changes
Looks pretty good, but move the route_id to a query parameter.

2019-07-31 22:06 UTC, consindo commented on js/data/LineData.js
> +    const route = encodeURIComponent(this.route_id)
What if there's no route_id specified?

2019-07-31 22:06 UTC, consindo commented on js/views/lines/LineList.jsx
> +      link.routeId,
Don't think this URL is currect

2019-07-31 22:06 UTC, consindo commented on js/views/shell/Content.jsx
> +            path="/l/:region/:agency_id/:route_id/:line_id"
Should be /l/:region/:agency_id/:line_id?route_id=whatever

2019-08-01 01:16 UTC, mjdavidson commented
@consindo sorry don't quite understand your aversion to route_id preference
https://github.com/dymajo/waka-server/blob/master/src/waka-worker/lines/regions/generic.ts#L12..L31
https://github.com/dymajo/waka-server/blob/master/src/waka-worker/stops/station.ts#L359..L377
all props needed to perform fetch by route_id are already supplied

2019-08-01 02:16 UTC, mjdavidson commented
fine.

2019-08-01 03:15 UTC, consindo approved these changes

2019-08-01 03:15 UTC, merged